# deploy 2 tier application with application server and database server using ansible playbook
---
# application server configuration
- name: Deployment of Web server 
  hosts: application_server
  become: yes
# variable for all packages and services to be installed and started on application server
  vars: 
   packages:
    - nginx
    - php
    - php-fpm
   services:
    - nginx
    - php-fpm
   web_file_path: /usr/share/nginx/html/info.php
# install nginx, php and php-fpm packages and start the services on application server
  tasks:
    - name: Install nginx and php, php-fpm packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
    - name: Start and enable nginx and php-fpm services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
# deploy php info file for testing on application server
    - name: Deploy php info file for testing
      ansible.builtin.copy:
        dest: "{{ web_file_path }}"
        content: |
         <?php 
         phpinfo(); 
         ?>
        owner: nginx
        group: nginx    
        mode: '0644'
  
# database server configuration
- name: Deployment of Database server
  hosts: database_server
  become: yes
# variable for database package and service to be installed and started on database server
  vars:
   db_package: mariadb105-server
   db_service: mariadb
   db_name: application_db

# install mariadb package and start the service on database server
  tasks: 
  - name: Install mariadb server package
    ansible.builtin.yum:
      name: "{{ db_package }}"
      state: present
  - name: Start and enable mariadb service
    ansible.builtin.systemd_service:
      name: "{{ db_service }}"
      state: started
      enabled: yes
  # create a database for application on database server
  - name: Create a database for application
    ansible.builtin.shell: |
      cmd: "mysql -u root -e 'CREATE DATABASE IF NOT EXISTS {{ db_name }};'"
    args: 
      executable: /bin/bash