# install nginx, start and enable nginx service 
---
- name: install niginx 
  hosts: localhost 
  become: yes # to run the tasks with root privileges
  tasks:
    - name: install nginx 
      ansible.bultin.dnf:
        name: nginx
        state: present
    - name: start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: started  
    - name: enable nginx service
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
    - name: check nginx service status
      ansible.builtin.systemd_service:  
        name: nginx
        state: started
    - name: create index.html file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
         <html>
          <head>
           <title> Welcome to Ansible Practice </title>
          </head>
          <body>
           <h1>Nginx is successfully installed and running!</h1>
          </body>
         </html>
