# This playbook creates a directory on the target machine (webserver) with specific permissions.
# yml file and inventory file should be in the same directory for the playbook to work.
---
- name: create a directory on target machine
  hosts: webserver
  become: yes
  tasks:
    - name: create a new directory inside ec2_user directory
      ansible.builtin.file:
        path: /home/ec2-user/data_dir
        state: directory
        mode: '0755'  