# [group_name]
# private_ip ansible_user=username ansible_ssh_private_key_file=/path/to/private/key.pem
[targetserver]
172.31.17.7 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/3tier.pem