# tasks file for apache
- name: Install httpd package
  ansible.builtin.dnf:
    name: "{{ apache_pkg }}"
    state: present

- name: start and enable httpd service
  ansible.builtin.systemd:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: create a simple index.html file
  ansible.builtin.copy:
    dest: "{{ apache_index_file }}"
    content: "<h1>Welcome to Ansible Apache Webserver</h1>"
    mode: '0644'