# create a file using the file module
--- 
- name: create a file 
  hosts: localhost
  tasks:
    - name: create a file using the file module
      ansible.builtin.file:
        path: /home/ec2-user/first_ansible_file.txt
        state: touch
        mode: '0644'