# This playbook is used to check connectivity to the hosts using the ping module.
---
- name: check connectivity
  hosts: localhost
  tasks: 
   - name: check connectivity using ping command
     ansible.builtin.ping:
    